name: 'Continuous Integration'

on:
  pull_request: ~
  push: ~

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      -
        name: 'Checkout The Code'
        uses: actions/checkout@v2
      -
        name: 'Install Dependencies'
        uses: php-actions/composer@v6
      - name: 'Unit Tests (PHP 8.0)'
        uses: php-actions/phpunit@v3
        with:
          php_version: '8.0'
      - name: 'Unit Tests (PHP 8.1)'
        uses: php-actions/phpunit@v3
        with:
          php_version: '8.1'
