name: 'Continuous Integration'

on:
  pull_request: ~
  push: ~

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
      - uses: php-actions/phpunit@v3
        with:
          php_version: '7.2'
      - uses: php-actions/phpunit@v3
        with:
          php_version: '7.3'
      - uses: php-actions/phpunit@v3
        with:
          php_version: '7.4'
      - uses: php-actions/phpunit@v3
        with:
          php_version: '8.0'
      - uses: php-actions/phpunit@v3
        with:
          php_version: '8.1'
